export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';
export const REGISTER_STORE_CLEAR = 'REGISTER_STORE_CLEAR';
export const REGISTER_SAVE_DATA = 'REGISTER_SAVE_DATA';
export const REGISTER_DISABLE_LOADER = 'REGISTER_DISABLE_LOADER';
export const REGISTER_REQUEST_EMAIL = 'REGISTER_REQUEST_EMAIL';
